name: Validation using Conda - CI

on: [push, pull_request]

jobs:
  build-env:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.0-rc.2

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN}}
        issue_message: "Saludos!"
        pr-message: "Revisando el PR...."
    - name: Test with pytest
      run: |
        conda install pytest
        conda install pandas
        pytest
